
spring:
  data:
    mongodb:
        host: 127.0.0.1
        port: 27017


camel:
  conponent:
      servlet:
        context-path: /api/*

jss:
  comet:
    fiLe:
      enabled: false
  weather:
      enabled: folso
  wiretap:
    enabled: false
  hello:
    enabled: false
  rest:
    enabled: true
  rest-dsl:
    enabled: true